CREATE TABLE User (
	UserID INT NOT NULL,
	UserName VARCHAR(50) NOT NULL,
	Mail VARCHAR(200) NOT NULL,
	Connected INT NOT NULL,
	FirstName VARCHAR(50) NULL,
	LastName VARCHAR(50) NULL,
	BirthDate DATE NULL,
	AvatarURI VARCHAR(200) NULL,
	Status INT NULL,
	Description TEXT NULL,
	PhoneNumber VARCHAR(12) NULL,
	PRIMARY KEY (
		UserID
	)
);

CREATE TABLE Channel (
	ChannelID INT NOT NULL,
	Name VARCHAR(75) NOT NULL,
	CreationDate DATETIME NOT NULL,
	PRIMARY KEY (
		ChannelID
	)
);